### ISSUE TITLE
How to use score_binder_rmsd_to_starting

### ISSUE THREAD

**Issue by amin-sagar** [Kuhlman-Lab/evopro#10]
Hello.
Thanks again for this awesome work.
Sorry for editing the issue. I posted the wrong file and error message earlier.
I am finding that for some complexes, the binding protein can move quite a bit from it's starting positions. So, I tried to use score_binder_rmsd_to_starting but I am not able to figure out how exactly to use it.
I tried
```
--num_iter 10
--pool_size 20
--num_gpus 2
--mpnn_temp 0.1
--score_file /home/amin/softwares/Protein-Design/EVOPRO/evopro/evopro/score_funcs/score_binder.py
--score_func score_binder
--rmsd_to_starting score_binder_rmsd_to_starting ../../Structures/Ahly_loop_pep_renum.pdb
--path_to_starting ../../Structures/Ahly_loop_pep_renum.pdb
--define_contact_area A57,A58,A59,A60,A61,A62,A63,A198,A200,A201,A204,A205,A206,A207,A214
--af2_preds_extra B
--mpnn_freq 5
--plot_scores_avg
--plot_confidences
```
But I get an error
```
Traceback (most recent call last):
  File "/home/amin/softwares/Protein-Design/EVOPRO/evopro/evopro/run/run_geneticalg_gpus.py", line 474, in <module>
    run_genetic_alg_gpus(input_dir, input_dir + flagsfile, scorefunc, starting_seqs, poolsizes=pool_sizes, 
  File "/home/amin/softwares/Protein-Design/EVOPRO/evopro/evopro/run/run_geneticalg_gpus.py", line 186, in run_genetic_alg_gpus
    rmsd_score_list.append(rmsd_to_starting_func(bscore[-2], rmsd_to_starting_pdb, dsobj=dsobj))
  File "/home/amin/softwares/Protein-Design/EVOPRO/evopro/evopro/score_funcs/score_binder.py", line 99, in score_binder_rmsd_to_starting
    rmsd_to_starting = get_rmsd(reslist1, pdb_string_starting, reslist2, pdb, ca_only=True, dsobj=dsobj)
  File "/home/amin/softwares/Protein-Design/EVOPRO/evopro/evopro/score_funcs/score_funcs.py", line 217, in get_rmsd
    rmsd = kabsch_rmsd(A, B, translate=translate)
  File "/home/amin/softwares/Protein-Design/EVOPRO/evopro/evopro/score_funcs/calculate_rmsd.py", line 387, in kabsch_rmsd
    P = kabsch_rotate(P, Q)
  File "/home/amin/softwares/Protein-Design/EVOPRO/evopro/evopro/score_funcs/calculate_rmsd.py", line 409, in kabsch_rotate
    U = kabsch(P, Q)
  File "/home/amin/softwares/Protein-Design/EVOPRO/evopro/evopro/score_funcs/calculate_rmsd.py", line 471, in kabsch
    C = np.dot(np.transpose(P), Q)
  File "<__array_function__ internals>", line 5, in dot
ValueError: shapes (3,303) and (17,3) not aligned: 303 (dim 1) != 17 (dim 0)
```
Could you please tell me the correct way of using this function.

Best,
Amin

**Comment by amin-sagar** [comment]
I think I understand.
I should have given the pdb of the binder protein alone, not the complex. 
It works now.
