### ISSUE TITLE
jaxlib.xla_extension.XlaRuntimeError: INTERNAL: Could not find the corresponding function

### ISSUE THREAD

**Issue by nongbaoting** [Kuhlman-Lab/evopro#11]
Hi, I am very interested in you wonderful project, but I encounter an error below:
```
 python   /dat1/apps/evopro/evopro-stable/evopro/run/run_geneticalg_gpus.py @evopro.flags
Reading ./residue_specs.json
No starting sequences file provided. Initial pool will be generated by random mutation.
initializing distributor
Iteration 1: Creating new sequences by random mutation.
initialization of process 0
WARNING:tensorflow:From /training/nong/app/miniconda3/envs/evopro/lib/python3.9/site-packages/tensorflow/python/autograph/pyct/static_analysis/liveness.py:83: Analyzer.lamba_check (from tensorflow.python.autograph.pyct.static_analysis.liveness) is deprecated and will be removed after 2023-09-23.
Instructions for updating:
Lambda fuctions will be no more assumed to be used in the statement where they are used, or at least in the same block. https://github.com/tensorflow/tensorflow/issues/56089
2023-07-20 09:28:24.561441: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:114] *** WARNING *** You are using ptxas 10.1.243, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.

2023-07-20 09:28:24.584896: W external/org_tensorflow/tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:231] Falling back to the CUDA driver for PTX compilation; ptxas does not support CC 8.6
2023-07-20 09:28:24.584928: W external/org_tensorflow/tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:234] Used ptxas at ptxas
2023-07-20 09:28:24.592690: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:628] failed to get PTX kernel "shift_right_logical" from module: CUDA_ERROR_NOT_FOUND: named symbol not found
2023-07-20 09:28:24.592757: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_stream_executor_client.cc:2153] Execution of replica 0 failed: INTERNAL: Could not find the corresponding function
Process Process-1:
Traceback (most recent call last):
  File "/training/nong/app/miniconda3/envs/evopro/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/training/nong/app/miniconda3/envs/evopro/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/dat1/apps/evopro/evopro-stable/evopro/utils/distributor.py", line 123, in _worker_loop
    f = f_init(proc_id, arg_file, lengths)
  File "/dat1/apps/evopro/alphafold-main/run/run_af2.py", line 139, in af2_init
    _ = predictStructure(
  File "/dat1/apps/evopro/alphafold-main/run/model.py", line 423, in predictStructure
    prediction = model_runner.predict(
  File "/training/nong/app/miniconda3/envs/evopro/lib/python3.9/site-packages/alphafold/model/model.py", line 169, in predict
    result = self.apply(self.params, jax.random.PRNGKey(random_seed), feat)
  File "/training/nong/app/miniconda3/envs/evopro/lib/python3.9/site-packages/jax/_src/random.py", line 132, in PRNGKey
    key = prng.seed_with_impl(impl, seed)
  File "/training/nong/app/miniconda3/envs/evopro/lib/python3.9/site-packages/jax/_src/prng.py", line 267, in seed_with_impl
    return random_seed(seed, impl=impl)
  File "/training/nong/app/miniconda3/envs/evopro/lib/python3.9/site-packages/jax/_src/prng.py", line 580, in random_seed
    return random_seed_p.bind(seeds_arr, impl=impl)
  File "/training/nong/app/miniconda3/envs/evopro/lib/python3.9/site-packages/jax/core.py", line 329, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
  File "/training/nong/app/miniconda3/envs/evopro/lib/python3.9/site-packages/jax/core.py", line 332, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/training/nong/app/miniconda3/envs/evopro/lib/python3.9/site-packages/jax/core.py", line 712, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/training/nong/app/miniconda3/envs/evopro/lib/python3.9/site-packages/jax/_src/prng.py", line 592, in random_seed_impl
    base_arr = random_seed_impl_base(seeds, impl=impl)
  File "/training/nong/app/miniconda3/envs/evopro/lib/python3.9/site-packages/jax/_src/prng.py", line 597, in random_seed_impl_base
    return seed(seeds)
  File "/training/nong/app/miniconda3/envs/evopro/lib/python3.9/site-packages/jax/_src/prng.py", line 832, in threefry_seed
    lax.shift_right_logical(seed, lax_internal._const(seed, 32)))
  File "/training/nong/app/miniconda3/envs/evopro/lib/python3.9/site-packages/jax/_src/lax/lax.py", line 515, in shift_right_logical
    return shift_right_logical_p.bind(x, y)
  File "/training/nong/app/miniconda3/envs/evopro/lib/python3.9/site-packages/jax/core.py", line 329, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
  File "/training/nong/app/miniconda3/envs/evopro/lib/python3.9/site-packages/jax/core.py", line 332, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/training/nong/app/miniconda3/envs/evopro/lib/python3.9/site-packages/jax/core.py", line 712, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/training/nong/app/miniconda3/envs/evopro/lib/python3.9/site-packages/jax/_src/dispatch.py", line 115, in apply_primitive
    return compiled_fun(*args)
  File "/training/nong/app/miniconda3/envs/evopro/lib/python3.9/site-packages/jax/_src/dispatch.py", line 200, in <lambda>
    return lambda *args, **kw: compiled(*args, **kw)[0]
  File "/training/nong/app/miniconda3/envs/evopro/lib/python3.9/site-packages/jax/_src/dispatch.py", line 895, in _execute_compiled
    out_flat = compiled.execute(in_flat)
jaxlib.xla_extension.XlaRuntimeError: INTERNAL: Could not find the corresponding function
```

**Comment by nongbaoting** [comment]
Sorry to bother you! I tried another Machine, and the issue did not appear.
