### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by SaTayv2** [Kuhlman-Lab/evopro#20]
Traceback (most recent call last):
  File "/home/samuel/Documents/EvoPro/evopro/evopro/run/generate_json.py", line 263, in <module>
    pdbids, chain_seqs = parse_pdbfile(args.pdb)
  File "/home/samuel/Documents/EvoPro/evopro/evopro/run/generate_json.py", line 32, in parse_pdbfile
    chains, residues, resindices = get_coordinates_pdb_old(filename, fil=True)
  File "/home/samuel/Documents/EvoPro/evopro/evopro/utils/pdb_parser.py", line 185, in get_coordinates_pdb_old
    with open(pdb,"r") as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType

When I try running python /path/to/evopro/run/generate_json.py @json.flags I get this error. I've already set the local paths at the top of each script and downloaded everything

**Comment by SaTayv2** [comment]
Hi for the input dir what input is it expecting?

**Comment by amritan1707** [comment]
It looks for af2.flags, evopro.flags, residue_specs.json, and other optional files based on what flags you are using.
