### ISSUE TITLE
raise BadZipFile("File is not a zip file")

### ISSUE THREAD

**Issue by SaTayv2** [Kuhlman-Lab/evopro#21]
Iteration 1: Creating new sequences.
work list [[['WNPPTFSPALLVVTEGDNATFTCSFSNTSESFHVVWHRESPSGQTDTLAAFPEDRSQPGQDSRFRVTQLPNGRDFHMSVVRARRNDSGTYVCGVISLAPKIQIKESLRAELRVTERRAE', 'DREEAKERIKELLELVKRVSEEERRELLREARRLAERVNDPEARRLVEELERLIKEL']], [['WNPPTFSPALLVVTEGDNATFTCSFSNTSESFHVVWHRESPSGQTDTLAAFPEDRSQPGQDSRFRVTQLPNGRDFHMSVVRARRNDSGTYVCGVISLAPKIQIKESLRAELRVTERRAE', 'DREEAKERIKEMLELVKRVSEEERRELLREEVKLAERVNDGEARNLVEELERLQKEL']], [['WNPPTFSPALLVVTEGDNATFTCSFSNTSESFHVVWHRESPSGQTDTLAAFPEDRSQPGQDSRFRVTQLPNGRDFHMSVVRARRNDSGTYVCGVISLAPKIQIKESLRAELRVTERRAE', 'DREEAKARIKEMLELVKRVSWEERRELLREARRLAERVNDFEARRLTEELERSIKEL']], [['WNPPTFSPALLVVTEGDNATFTCSFSNTSESFHVVWHRESPSGQTDTLAAFPEDRSQPGQDSRFRVTQLPNGRDFHMSVVRARRNDSGTYVCGVISLAPKIQIKESLRAELRVTERRAE', 'DREEAKERRKHLLELVKRVSLEERRELLREARRVAERVNDPEAARLVQELERLRKEL']], [['WNPPTFSPALLVVTEGDNATFTCSFSNTSESFHVVWHRESPSGQTDTLAAFPEDRSQPGQDSRFRVTQLPNGRDFHMSVVRARRNDSGTYVCGVISLAPKIQIKESLRAELRVTERRAE', 'DREEAKERIKELLELVKSVSEPERRELLFEMRRLAERVNDPEARRLVSSLESLIKGL']], [['WNPPTFSPALLVVTEGDNATFTCSFSNTSESFHVVWHRESPSGQTDTLAAFPEDRSQPGQDSRFRVTQLPNGRDFHMSVVRARRNDSGTYVCGVISLAPKIQIKESLRAELRVTERRAE', 'DREEAKERIKEELELVKRVSEEERRELLREARRIAERVNDPDSSRIVEELERLIKEL']]]
initialization of process 0
Process Process-1:
Traceback (most recent call last):
  File "/home/samuel/anaconda3/envs/evopro/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/samuel/anaconda3/envs/evopro/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/samuel/Documents/evopro/evopro/utils/distributor.py", line 116, in _worker_loop
    f = f_init(proc_id, arg_file, lengths)
  File "/home/samuel/Documents/alphafold/run/run_af2.py", line 125, in af2_init
    model_runner = getModelRunner(
  File "/home/samuel/Documents/alphafold/run/model.py", line 88, in getModelRunner
    params = data.get_model_haiku_params(model_name, params_dir)
  File "/home/samuel/anaconda3/envs/evopro/lib/python3.9/site-packages/alphafold/model/data.py", line 31, in get_model_haiku_params
    params = np.load(io.BytesIO(f.read()), allow_pickle=False)
  File "/home/samuel/anaconda3/envs/evopro/lib/python3.9/site-packages/numpy/lib/npyio.py", line 444, in load
    ret = NpzFile(fid, own_fid=own_fid, allow_pickle=allow_pickle,
  File "/home/samuel/anaconda3/envs/evopro/lib/python3.9/site-packages/numpy/lib/npyio.py", line 190, in __init__
    _zip = zipfile_factory(fid)
  File "/home/samuel/anaconda3/envs/evopro/lib/python3.9/site-packages/numpy/lib/npyio.py", line 103, in zipfile_factory
    return zipfile.ZipFile(file, *args, **kwargs)
  File "/home/samuel/anaconda3/envs/evopro/lib/python3.9/zipfile.py", line 1266, in __init__
    self._RealGetContents()
  File "/home/samuel/anaconda3/envs/evopro/lib/python3.9/zipfile.py", line 1333, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

Getting this error after running the evopro line.
af2.flags:
--output_dir outputs/predictions
--params_dir /home/samuel/Documents/alphafold/alphafold/model_weights
--compress_output
--use_ptm
--msa_mode single_sequence
--num_models 1
--max_recycle 1
--save_timing
--design_run
evopro.flags
--num_iter 3
--pool_size 6
--num_gpus 1
--score_file /home/samuel/Documents/evopro/evopro/run/score_file.py
--score_func score_overall
--rmsd_func score_binder_rmsd
--af2_preds_extra B
--define_contact_area A31-A58,A88-A108
--mpnn_freq 2
--plot_scores_avg
--plot_confidences

I don't understand which file is supposed to be a zip file

**Comment by amritan1707** [comment]
Hi, I think the AF2 runner script is looking for .npz files of model weights - do you have those in the params_dir?
